name: ARMOR Checkers Reusable Workflow

on:
  workflow_call:
    inputs:
      base-sha:
        required: false
        type: string
        default: ''
      head-sha:
        required: false
        type: string
        default: ''
      branch-name:
        required: false
        type: string
        default: ''
      armor-checker-options:
        required: false
        type: string
        default: ''
      approvers-file:
        required: false
        type: string
        default: '.github/armor-approvers.txt'
        description: "Path to the approvers file in the caller's repo (relative to repo root)"

permissions:
  contents: read
  pull-requests: read

jobs:
  prepare:
    name: Prepare ARMOR Checkers Parameters
    uses: qualcomm/armor-checkers/.github/workflows/set_checker_vars.yml@v1
    with:
      base-sha: ${{ inputs.base-sha }}
      head-sha: ${{ inputs.head-sha }}
      branch-name: ${{ inputs.branch-name }}
      armor-checker-options: ${{ inputs.armor-checker-options }}

  armor-api-check:
    name: Run API Check
    needs: prepare
    if: ${{ needs.prepare.outputs.mergeable != 'false' }}
    runs-on: ${{ fromJSON(needs.prepare.outputs.runner_json) }}
    steps:
      - name: Run API Compatibility Check
        uses: qualcomm/armor-checkers/.github/actions/api_checker@v1
        with:
          event-name:  ${{ needs.prepare.outputs.event_name }}
          head-sha:    ${{ needs.prepare.outputs.head_sha }}
          base-sha:    ${{ needs.prepare.outputs.base_sha }}
          ref:         ${{ needs.prepare.outputs.ref }}
          repo:        ${{ needs.prepare.outputs.repo }}
          branch-name: ${{ needs.prepare.outputs.branch_name }}
          approvers-file:  ${{ inputs.approvers-file }}

  abi-check:
    name: Run ABI check
    needs: prepare
    if: ${{ needs.prepare.outputs.mergeable != 'false' }}
    runs-on: ${{ fromJSON(needs.prepare.outputs.runner_json) }}
    steps:
      - name: Run ABI Compatibility Check
        uses: qualcomm/armor-checkers/.github/actions/abi_checker@v1
        with:
          event-name:   ${{ needs.prepare.outputs.event_name }}
          head-sha:     ${{ needs.prepare.outputs.head_sha }}
          base-sha:     ${{ needs.prepare.outputs.base_sha }}
          ref:          ${{ needs.prepare.outputs.ref }}
          repo:         ${{ needs.prepare.outputs.repo }}
          branch-name:  ${{ needs.prepare.outputs.branch_name }}
          build-script: ${{ needs.prepare.outputs.build_script }}